### ISSUE TITLE
Does not build with ghc 8

### ISSUE THREAD

**Issue by idontgetoutmuch** [diagrams/diagrams-haddock#28]
```
cabal: Could not resolve dependencies:
trying: diagrams-haddock-0.3.0.10 (user goal)
next goal: base (dependency of diagrams-haddock-0.3.0.10)
rejecting: base-4.9.0.0/installed-4.9... (conflict: diagrams-haddock =>
base>=4.4 && <4.9)
rejecting: base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0,
base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0,
base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0,
base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0,
base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from non-upgradeable
package requires installed instance)
Dependency tree exhaustively searched.
```

**Comment by byorgey** [comment]
Thanks for the report. We are aware of the need to upgrade everything for GHC 8.  For a while we were waiting for upstream packages to update.  I'm now working on getting everything updated.  Nothing difficult, just lots of fiddly things to change.

**Comment by idontgetoutmuch** [comment]
Hi Brent, Any news on this? I'd like to use it for the Kalman filter package I am working on.

**Comment by byorgey** [comment]
I guess the news is that @cchalmers just fixed it? =)  Well, in git at least.  `diagrams-builder` and `diagrams-haddock` have been giving me trouble.  I'll have to look at making new point releases of them next.

**Comment by cchalmers** [comment]
Yeah, it works for me but Travis seems to give a different build error for each version. (I don't know what to make of https://travis-ci.org/diagrams/diagrams-haddock/jobs/154830965). Maybe it would be easier drop older ghc support for this and `builder`?

**Comment by byorgey** [comment]
Actually that travis error is straightforward to decipher if you scroll all the way to the bottom: `haskell-src-exts-simple` requires `base >= 4.7`.  So yeah, I think dropping support for older GHCs is the way to go.  Honestly I don't even know why we are still testing `diagrams-haddock` on GHC 7.6.
